[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.55.6"
HUGO_THEME = "hugo-cactus-theme"
HUGO_BASE_URL = "https://managume.netlify.com"

[context.production.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.6"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.6"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "http://blog.managu.me"
to = "http://www.managu.me/blog"
status = 200
force = false

[[redirects]]
from = "http://blog.managu.me/*"
to = "http://www.managu.me/blog/:splat"
status = 200
force = true

[[redirects]]
from = "http://managume.netlify.com/*"
to = "http://www.managu.me/:splat"
status = 301